# Generated by Django 5.1 on 2024-08-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamdetection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='phone number'),
        ),
    ]
