# Generated by Django 5.1 on 2024-08-20 12:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamdetection', '0004_alter_myuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(default=uuid.uuid4, max_length=15, unique=True, verbose_name='phone number'),
        ),
    ]
