# Generated by Django 5.1 on 2024-08-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamdetection', '0005_alter_myuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='phone number'),
        ),
    ]
